name: Frontend Build and Push

on:
  push:
    branches: [main, develop]
    paths: ['frontend/**']
  pull_request:
    branches: [main]
    paths: ['frontend/**']
  workflow_dispatch:

env:
  REGISTRY_NAME: acrburgerbuilder
  IMAGE_NAME: frontend
  WORKING_DIRECTORY: ./azure-3tier-aca/frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: npm ci

    - name: Run tests
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: npm run test:ci

    - name: Run lint
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: npm run lint

    - name: Build application
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Generate image tags
      id: meta
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "tags=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
        else
          echo "tags=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.WORKING_DIRECTORY }}
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Container App (Production)
      if: github.ref == 'refs/heads/main'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.0
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az containerapp update \
            --name ca-frontend \
            --resource-group rg-burgerbuilder-prod \
            --image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}